# Generated by Django 3.0.6 on 2020-05-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_admissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firstcarousel',
        ),
        migrations.DeleteModel(
            name='Resultphoto',
        ),
    ]
