# Generated by Django 3.0.6 on 2020-05-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200531_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='course',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='firstname',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='surname',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
