# Generated by Django 3.0.6 on 2020-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200531_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='mobnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
